language: php

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit --configuration phpunit.xml.dist --coverage-text
  - ./signaleHandlerRunner.sh

notifications:
  email: false

install:
  - composer install --prefer-source
